=== LegalChocolates/xml_lab/data/schedule.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Root Element -->
<!ELEMENT schedule (days, periods, courses) >
<!ATTLIST schedule
    set  CDATA #REQUIRED
    term CDATA #REQUIRED
>

<!-- Days of the Week -->
<!ELEMENT days (day)* >
<!ELEMENT day  (booking)* >
<!ATTLIST day
    type (mon|tue|wed|thu|fri) #REQUIRED
>


<!-- A Time-slot in a Day ( e.g. 10:30 ) -->
<!ELEMENT periods (period)* >
<!ELEMENT period  (booking)* >
<!ATTLIST period
    time (830|930|1030|1130|1230|1330|1430|1530|1630) #REQUIRED
>


<!-- A Course -->
<!ELEMENT courses (course)* >
<!ELEMENT course  (booking)* >
<!ATTLIST course
    code CDATA #REQUIRED
>

<!-- A Booking for a day, period and course -->
<!ELEMENT booking EMPTY >
<!ATTLIST booking
        timeslot    (830|930|1030|1130|1230|1330|1430|1530|1630) #IMPLIED
        dayofweek   (mon|tue|wed|thu|fri)                        #IMPLIED
        coursename  CDATA                                        #IMPLIED
        instructor  CDATA                                        #REQUIRED
        room        CDATA                                        #REQUIRED
        bookingtype CDATA                                        #REQUIRED
>

=== LegalChocolates/xml_lab/data/courses.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE courses SYSTEM "schedule.dtd">
<courses>
    <!-- Monday -->
    <course code="BLAW 3600">
        <booking instructor="Catherine Ryan" room="SW3 4785" bookingtype="Lab"/>
    </course>
    <course code="COMP 4735">
        <booking instructor="Mirela Gutica"  room="SW1 1205" bookingtype="Lec"/>
    </course>
    <course code="COMP 4735">
        <booking instructor="Mirela Gutica"  room="SE12 320" bookingtype="Lab"/>
    </course>

    <!-- Tuesday -->
    <course code="COMP 4977">
        <booking instructor="D`arcy Smith" room="SE12 325" bookingtype="Sem"/>
    </course>
    <course code="COMP 4560">
        <booking instructor="Brenda Fine"  room="SW5 1850" bookingtype="Lec"/>
    </course>
    <course code="COMP 4711">
        <booking instructor="James Parry"  room="SW5 1850" bookingtype="Lec"/>
    </course>
    <course code="COMP 4560">
        <booking instructor="Joseph Lo"    room="SE12 322" bookingtype="Lab"/>
    </course>

    <!-- Thursday -->
    <course code="COMP 4976">
        <booking instructor="Medhat Elmasry" room="SE12 308" bookingtype="Sem"/>
    </course>
    
</courses>

=== LegalChocolates/xml_lab/data/periods.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE periods SYSTEM "schedule.dtd">
<periods>
    <period time="830">
        <booking instructor="D`arcy Smith"   room="SE12 325" bookingtype="Sem" dayofweek="tue" coursename="COMP 4977"/>
        <booking instructor="Medhat Elmasry" room="SE12 308" bookingtype="Sem" dayofweek="thu" coursename="COMP 4976"/>
        <booking instructor="Catherine Ryan" room="SW5 1840" bookingtype="Lec" dayofweek="fri" coursename="BLAW 3600"/>
    </period>
    <period time="1130">
        <booking instructor="Mirela Gutica" room="SW1 1205" bookingtype="Lec" dayofweek="mon" coursename="COMP 4735"/>
        <booking instructor="Brenda Fine"   room="SW5 1850" bookingtype="Lec" dayofweek="tue" coursename="COMP 4560"/>
        <booking instructor="Mierla Gutica" room="SW3 1710" bookingtype="Lec" dayofweek="thu" coursename="COMP 4735"/>
    </period>
    <period time="1230">
        <booking instructor="Mierla Gutica"  room="SE12 320" bookingtype="Lab" dayofweek="mon" coursename="COMP 4735"/>
        <booking instructor="Medhat Elmasry" room="SE12 308" bookingtype="Sem" dayofweek="thu" coursename="COMP 4976"/>
        <booking instructor="Brenda Fine"    room="SW3 1750" bookingtype="Lec" dayofweek="fri" coursename="COMP 4560"/>
    </period>
</periods>

=== LegalChocolates/xml_lab/data/days.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE days SYSTEM "schedule.dtd">
<days>
    <day type="mon">
        <booking instructor="Catherine Ryan" room="SW3 4785" bookingtype="Lab" timeslot="930"  coursename="BLAW 3600"/>
        <booking instructor="Mirela Gutica"  room="SW1 1205" bookingtype="Lec" timeslot="1130" coursename="COMP 4735"/>
        <booking instructor="Mirela Gutica"  room="SE12 320" bookingtype="Lab" timeslot="1230" coursename="COMP 4735"/>
    </day>
    <day type="tue">
        <booking instructor="D`arcy Smith" room="SE12 325" bookingtype="Lab" timeslot="830"  coursename="COMP 4977"/>
        <booking instructor="Brenda Fine"  room="SW5 1850" bookingtype="Lec" timeslot="1130" coursename="COMP 4560"/>
        <booking instructor="James Parry"  room="SW5 1840" bookingtype="Lec" timeslot="1430" coursename="COMP 4711"/>
        <booking instructor="Joseph Lo"    room="SE12 322" bookingtype="Lab" timeslot="1530" coursename="COMP 4560"/>
    </day>
    <day type="thu">
        <booking instructor="Medhat Elmasry" room="SE12 308" bookingtype="Sem" timeslot="830"  coursename="COMP 4976"/>
        <booking instructor="Mirela Gutica"  room="SW3 1750" bookingtype="Lec" timeslot="1130" coursename="COMP 4735"/>
        <booking instructor="Medhat Elmasry" room="SE12 308" bookingtype="Sem" timeslot="1230" coursename="COMP 4976"/>
    </day>
</days>
